paths:
  /yamareco-get-list:
    post:
      parameters:
        - in: body
          name: body
          schema:
            type: object
      responses:
        200:
          description: Success
          schema:
            type: object

  /yamareco-get-user:
    post:
      parameters:
        - in: body
          name: body
          schema:
            type: object
      responses:
        200:
          description: Success
          schema:
            type: object

  /yamareco-get-gpx:
    get:
      responses:
        200:
          description: Success
          schema:
            type: object
